/* eslint-disable react/jsx-key */
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { fetchEntries } from '../utils/contentfulProducts';
import Products from '../Components/Products';


export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Products</h1>
        <div className={styles.grid}>
          {products.map((product) => (
            <div>
              <Products key={product.id}
              productId={product.id}
              productName1={product.productName1} 
              productDescription={product.productDescription}
              productPrice={product.productPrice}
              productImage={product.productImage.fields} />
            </div>
          ))}
        </div>
        
      </main>

    </div>
  )
}
export async function getStaticProps() {
  const res = await fetchEntries()
  const products = await res.map((p) => {
    return p.fields
  })

  return {
    props: {
      products,
    },
  }
}