/* eslint-disable react/jsx-key */
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { fetchEntries } from '../utils/contentfulProducts';
import Products from '../Components/Products';
import Link from 'next/link';

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href="/products">
          <a><h3>Products</h3></a>
        </Link>
      </header>

      <main className={styles.main}>
        <div className='products'>
          <h1>Products</h1>
          {products.map((product) => (
            <div>
              <Products key={product.id}
              productId={product.id}
              productName1={product.productName1} 
              productDescription={product.productDescription}
              productPrice={product.productPrice}
              productImage={product.productImage.fields} />
            </div>
          ))}
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export async function getStaticProps() {
  const res = await fetchEntries()
  const products = await res.map((p) => {
    return p.fields
  })

  return {
    props: {
      products,
    },
  }
}